In [1]:
import torch

a = torch.randn(4, 4)
a




tensor([[ 0.4915, -0.3582,  1.3161,  0.4297],
        [-0.0449, -1.1173,  0.0693,  0.0666],
        [ 0.6243,  0.8208, -0.1563,  1.2695],
        [-1.9026, -0.1952, -1.6501,  0.1231]])

In [2]:
torch.argsort(a, dim=1)

tensor([[1, 3, 0, 2],
        [1, 0, 3, 2],
        [2, 0, 1, 3],
        [0, 2, 1, 3]])

In [3]:
torch.argsort(torch.argsort(a, dim=1), dim=1)

tensor([[2, 0, 3, 1],
        [1, 0, 3, 2],
        [1, 2, 0, 3],
        [0, 2, 1, 3]])

In [5]:
torch.argsort(a, dim=1)[:,:2]

tensor([[1, 3],
        [1, 0],
        [2, 0],
        [0, 2]])